config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/WorkTypesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\WorkType;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * WorkTypes Model
 *
 * @property \Cake\ORM\Association\BelongsToMany $Contracts
 */
class WorkTypesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('work_types');
        $this->displayField('nome');
        $this->primaryKey('id');
        
        $this->addBehavior('Timestamp');

        $this->belongsTo('PaymentTypes', [
            'foreignKey' => 'p_type_default',
            'joinType' => 'INNER'
        ]);
        
        $this->hasMany('WorkTypeInstances', [
            'foreignKey' => 'work_type_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('nome', 'create')
            ->notEmpty('nome');

        $validator
            ->requirePresence('codice', 'create')
            ->notEmpty('codice');

        $validator
            ->allowEmpty('descrizione');

        $validator
            ->integer('durata')
            ->allowEmpty('durata');

        return $validator;
    }
    
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['p_type_default'], 'PaymentTypes'));
        return $rules;
    }
}

src/Controller/WorkTypesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Core\Configure;

/**
 * WorkTypes Controller
 *
 * @property \App\Model\Table\WorkTypesTable $WorkTypes
 */
class WorkTypesController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['PaymentTypes']
        ];
        $workTypes = $this->paginate($this->WorkTypes);

        $this->set(compact('workTypes'));
        $this->set('_serialize', ['workTypes']);
    }

    /**
     * View method
     *
     * @param string|null $id Work Type id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $workType = $this->WorkTypes->get($id, [
            'contain' => ['WorkTypeInstances']
        ]);

        $this->set('workType', $workType);
        $this->set('_serialize', ['workType']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->set('form_templates', Configure::read('Templates'));

        $workType = $this->WorkTypes->newEntity();
        if ($this->request->is('post')) {
            $workType = $this->WorkTypes->patchEntity($workType, $this->request->data);
            if ($this->WorkTypes->save($workType)) {
                $this->Flash->success(__('The work type has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The work type could not be saved. Please, try again.'));
            }
        }
        $payment_types=$this->WorkTypes->PaymentTypes->find('list', ['keyField' => 'id', 
                    'valueField' => 'nome', 
                    'limit' => 200]);
        $mesi = ['1' => '1 mese',
            '2' => '2 mesi',
            '3' => '3 mesi',
            '4' => '4 mesi',
            '5' => '5 mesi',
            '6' => '6 mesi',
            '7' => '7 mesi',
            '8' => '8 mesi',
            '9' => '9 mesi',
            '10' => '10 mesi',
            '11' => '11 mesi',
            '12' => '12 mesi',
            '18' => '18 mesi',
            '24' => '24 mesi',
            ];
        
        $this->set('mesi', $mesi);
        $this->set(compact('workType', 'payment_types'));
        $this->set('_serialize', ['workType']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Work Type id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $this->set('form_templates', Configure::read('Templates'));

        $workType = $this->WorkTypes->get($id, [
            
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $workType = $this->WorkTypes->patchEntity($workType, $this->request->data);
            if ($this->WorkTypes->save($workType)) {
                $this->Flash->success(__('The work type has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The work type could not be saved. Please, try again.'));
            }
        }
        //$contracts = $this->WorkTypes->Contracts->find('list', ['limit' => 200]);
        $payment_types=$this->WorkTypes->PaymentTypes->find('list', ['keyField' => 'id', 
                    'valueField' => 'nome', 
                    'limit' => 200]);
        $mesi = ['1' => '1 mese',
            '2' => '2 mesi',
            '3' => '3 mesi',
            '4' => '4 mesi',
            '5' => '5 mesi',
            '6' => '6 mesi',
            '7' => '7 mesi',
            '8' => '8 mesi',
            '9' => '9 mesi',
            '10' => '10 mesi',
            '11' => '11 mesi',
            '12' => '12 mesi',
            '18' => '18 mesi',
            '24' => '24 mesi',
            ];
        
        $this->set('mesi', $mesi);
        $this->set(compact('workType', 'payment_types'));
        $this->set('_serialize', ['workType']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Work Type id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->set('form_templates', Configure::read('Templates'));

        $this->request->allowMethod(['post', 'delete']);
        $workType = $this->WorkTypes->get($id);
        if ($this->WorkTypes->delete($workType)) {
            $this->Flash->success(__('The work type has been deleted.'));
        } else {
            $this->Flash->error(__('The work type could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
    
    public function getNomi() {
        $str = $this->request->data['worktype-str'];


        $names = $this->WorkTypes->find('list', [
            'conditions' => ['WorkTypes.nome LIKE' => '%'.$str.'%'],
            'keyField' => 'id', 
            'valueField' => 'nome',
            'recursive' => -1,
        ]);
        $this->set('names',$names);
        $this->viewBuilder()->layout('ajax');
    }
}

src/Template/WorkTypes/add.ctp
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Aggiungi tipo lavoro</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                  Inserimento dati 
            </div>
            <div class="panel-body">    <?= $this->Form->create($workType) ?>
                    <?php $this->Form->templates($form_templates['fullForm']); ?>

    <fieldset>
        <div class="row">
            <div class="col-lg-4">
                <?= $this->Form->input('nome'); ?>
                <?= $this->Form->input('descrizione'); ?>
            </div>
            <div class="col-lg-4">
                <?= $this->Form->input('codice'); ?>
                <?= $this->Form->label('durata', 'Ricorrenza di default'); ?>
                <?= $this->Form->input('durata', ['options' => $mesi, 'label' => false, 'empty' => true]); ?>            
            </div>
            <div class="col-lg-4">
                <?= $this->Form->label('p_type_default', 'Tipo pagamento di default'); ?>
                <?= $this->Form->input('p_type_default', ['options' => $payment_types, 'label' => false]); ?>          
            </div>
        </div>

    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div></div></div></div>

src/Template/WorkTypes/edit.ctp
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Modifica tipo di lavoro </h1>
        <h4> <?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $workType->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $workType->id)]
            )
        ?></h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                  Modifica dati
            </div>
            <div class="panel-body">    <?= $this->Form->create($workType) ?>
                    <?php $this->Form->templates($form_templates['fullForm']); ?>

    <fieldset>
        <div class="row">
            <div class="col-lg-4">
                <?= $this->Form->input('nome'); ?>
                <?= $this->Form->input('descrizione'); ?>
            </div>
            <div class="col-lg-4">
                <?= $this->Form->input('codice'); ?>
                <?= $this->Form->label('durata', 'Ricorrenza di default'); ?>
                <?= $this->Form->input('durata', ['options' => $mesi, 'label' => false, 'empty' => true]); ?>            
            </div>
            <div class="col-lg-4">
                <?= $this->Form->label('p_type_default', 'Tipo pagamento di default'); ?>
                <?= $this->Form->input('p_type_default', ['options' => $payment_types, 'label' => false]); ?>          
            </div>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/WorkTypes/get_nomi.ctp
<ul class="">
<?php foreach ($names as $key => $value): ?>
    <li class='worktype_select' value="<?php echo $key; ?>"><?php echo $value; ?></li>
<?php endforeach; ?>
</ul>

src/Template/WorkTypes/index.ctp
<div class="row">
    <div class="col-lg-6">
        <h1 class="page-header">Tipi di lavoro</h1>
    </div>
    <div class="col-lg-6">
        <?= $this->Html->link(__('Aggiungi tipo di lavoro'), ['controller' => 'WorkTypes', 'action' => 'add'], ['class'=>'page-header pull-right']) ?>
    </div>
</div>
<div class="panel-body">    
    <table class="table table-striped" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th><?= $this->Paginator->sort('nome') ?></th>
                <th><?= $this->Paginator->sort('codice') ?></th>
                <th><?= $this->Paginator->sort('descrizione') ?></th>
                <th><?= $this->Paginator->sort('payment_type_default') ?></th>
                <th><?= $this->Paginator->sort('durata') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($workTypes as $workType): ?>
            <tr>
                <td><?= h($workType->nome) ?></td>
                <td><?= h($workType->codice) ?></td>
                <td><?= h($workType->descrizione) ?></td>
                <td><?= h($workType->payment_type->nome) ?></td>
                <td><?= $this->Number->format($workType->durata) ?> mesi</td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $workType->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $workType->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $workType->id], ['confirm' => __('Are you sure you want to delete # {0}?', $workType->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>

src/Template/WorkTypes/view.ctp
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= h('Tipo lavoro '.$workType->nome) ?></h1>
        <h4><?= $this->Html->link(__('Edit '), ['action' => 'edit', $workType->id]) ?> </h4>
        <h4><?= $this->Form->postLink(__('Delete '), ['action' => 'delete', $workType->id], ['confirm' => __('Are you sure you want to delete # {0}?', $workType->id)]) ?> </h4>
    </div>
</div>
    <div class="panel-body">

    <table class="table table-striped">
        <tr>
            <th><?= __('Nome') ?></th>
            <td><?= h($workType->nome) ?></td>
        </tr>
        <tr>
            <th><?= __('Codice') ?></th>
            <td><?= h($workType->codice) ?></td>
        </tr>
        <tr>
            <th><?= __('Descrizione') ?></th>
            <td><?= h($workType->descrizione) ?></td>
        </tr>
        <tr>
            <th><?= __('Id') ?></th>
            <td><?= $this->Number->format($workType->id) ?></td>
        </tr>
        <tr>
            <th><?= __('Durata') ?></th>
            <td><?= $this->Number->format($workType->durata) ?></td>
        </tr>
    </table>
    <div class="related">
        <h4><?= __('Related Contracts') ?></h4>
        <?php if (!empty($workType->contracts)): ?>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th><?= __('Id') ?></th>
                <th><?= __('Status Id') ?></th>
                <th><?= __('Numero') ?></th>
                <th><?= __('Importo') ?></th>
                <th><?= __('Note') ?></th>
                <th><?= __('Agent Id') ?></th>
                <th><?= __('Client Id') ?></th>
                <th><?= __('Created') ?></th>
                <th><?= __('Modified') ?></th>
                <th><?= __('Provvigione') ?></th>
                <th><?= __('Bonus') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($workType->contracts as $contracts): ?>
            <tr>
                <td><?= h($contracts->id) ?></td>
                <td><?= h($contracts->status_id) ?></td>
                <td><?= h($contracts->numero) ?></td>
                <td>€ <?= h($contracts->importo) ?></td>
                <td><?= h($contracts->note) ?></td>
                <td><?= h($contracts->agent_id) ?></td>
                <td><?= h($contracts->client_id) ?></td>
                <td><?= h($contracts->created) ?></td>
                <td><?= h($contracts->modified) ?></td>
                <td><?= h($contracts->provvigione) ?>%</td>
                <td><?= h($contracts->bonus) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'Contracts', 'action' => 'view', $contracts->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['controller' => 'Contracts', 'action' => 'edit', $contracts->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['controller' => 'Contracts', 'action' => 'delete', $contracts->id], ['confirm' => __('Are you sure you want to delete # {0}?', $contracts->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
</div>